const TOGGLE_READ_MORE_PANEL = 'TOGGLE_READ_MORE_PANEL';
const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
const OPEN_DRAWER = 'OPEN_DRAWER';
const TOGGLE_NEWS_LIST_MODAL = 'TOGGLE_NEWS_LIST_MODAL';
const OPEN_NEWS_LIST_MODAL = 'OPEN_NEWS_LIST_MODAL';
const CLOSE_NEWS_LIST_MODAL = 'CLOSE_NEWS_LIST_MODAL';
const SAVE_SELECTED_NEWS = 'SAVE_SELECTED_NEWS';
const SAVE_SOCIAL_SHARE_DATA = 'SAVE_SOCIAL_SHARE_DATA';

export { SAVE_SOCIAL_SHARE_DATA, OPEN_DRAWER, TOGGLE_DRAWER, TOGGLE_READ_MORE_PANEL, TOGGLE_NEWS_LIST_MODAL, OPEN_NEWS_LIST_MODAL, CLOSE_NEWS_LIST_MODAL, SAVE_SELECTED_NEWS }